<a href="https://colab.research.google.com/github/dscamacho333/Data_Science_Course/blob/main/Pandas_E_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Documentation Link: https://pandas.pydata.org/docs/reference/index.html

In [ ]:
# Mount Google Drive

from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

# CSV

## Reading CSV (Importing)

In [ ]:
# Library to handle different file types and handle data

import pandas as pd

In [ ]:
# Library to check what encoding file is under

import chardet

In [ ]:
# Find out what encoding file is under (Important to avoid encoding exceptions)

with open('/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/CSV Datasets/superstore_data.csv', 'rb') as file:

  print(chardet.detect(file.read()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [ ]:
# How to import CSV separated by colon

super_store_data_colon_separated : pd.DataFrame = pd.read_csv(
    filepath_or_buffer='/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/CSV Datasets/superstore_data.csv', # Param to indicate what file we will be reading
    sep=',', # Param to indicate what the separator for the csv is
    usecols=['Id', 'Year_Birth', 'Education'], # Param to select chosen columns (could be the name as string or position as int)
    nrows=5, # Param to import n rows only,
    encoding='ascii' # Param to inidcate what encoding file has
)

In [ ]:
super_store_data_colon_separated

      Id  Year_Birth   Education
0   1826        1970  Graduation
1      1        1961  Graduation
2  10476        1958  Graduation
3   1386        1967  Graduation
4   5371        1989  Graduation

In [ ]:
# How to import CSV separated by semicolon

super_store_data_semicolon_separated : pd.DataFrame = pd.read_csv(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/CSV Datasets/superstore_data_punto_coma.csv',
    sep=';'
)

In [ ]:
super_store_data_semicolon_separated.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

## Writing CSV (Exporting)

In [ ]:
super_store_data_colon_separated.to_csv(
    'super_store_data_colon_separated_selected_columns_and_rows.csv',
    sep=',',
    index=False
)

In [ ]:
pd.read_csv(
    'super_store_data_colon_separated_selected_columns_and_rows.csv'
)

      Id  Year_Birth   Education
0   1826        1970  Graduation
1      1        1961  Graduation
2  10476        1958  Graduation
3   1386        1967  Graduation
4   5371        1989  Graduation

## Practice 01

In [ ]:
health_dataset : pd.DataFrame = pd.read_csv(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/CSV Datasets/datos_sus.csv',
    sep=';',
    encoding='ISO-8859-1',
    skiprows=3, # Skip rows at the begining
    skipfooter=9, # Skip row at the end
    engine='python' # Needed when using skipfooter
)

In [ ]:
health_dataset

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

# Excel

## Read Excel (Importing)

In [ ]:
co2_emissions_excel_data_url : str = '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/Excel Datasets/emisiones_CO2.xlsx'

In [ ]:
# Check what sheets are on the excel

pd.ExcelFile(
    co2_emissions_excel_data_url
).sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [ ]:
co2_emissions_excel_sheet_dataframe : pd.DataFrame = pd.read_excel(
    co2_emissions_excel_data_url,
    sheet_name=0
)

In [ ]:
co2_emissions_excel_sheet_dataframe

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [ ]:
percapita_emissions_excel_sheet_dataframe : pd.DataFrame = pd.read_excel(
    co2_emissions_excel_data_url,
    sheet_name=1
)

In [ ]:
percapita_emissions_excel_sheet_dataframe

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
0,Afganistán,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [ ]:
sources_excel_sheet_dataframe : pd.DataFrame = pd.read_excel(
    co2_emissions_excel_data_url,
    sheet_name=2,
    usecols='A:D',
    nrows=5
)

In [ ]:
sources_excel_sheet_dataframe

         País ISO 3166-1 alpha-3   Año   Total
0  Afganistán                AFG  1750  [NONE]
1  Afganistán                AFG  1751  [NONE]
2  Afganistán                AFG  1752  [NONE]
3  Afganistán                AFG  1753  [NONE]
4  Afganistán                AFG  1754  [NONE]

## Write Excel (Exporting)

In [ ]:
sources_excel_sheet_dataframe.to_excel(
    'sources.xlsx',
    index=False
)

In [ ]:
pd.read_excel(
    'sources.xlsx'
)

         País ISO 3166-1 alpha-3   Año   Total
0  Afganistán                AFG  1750  [NONE]
1  Afganistán                AFG  1751  [NONE]
2  Afganistán                AFG  1752  [NONE]
3  Afganistán                AFG  1753  [NONE]
4  Afganistán                AFG  1754  [NONE]

# JSON

## Reading JSON (Importing)

In [ ]:
# No embedded data within JSON

patients_no_embedded_data_json : pd.DataFrame = pd.read_json(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/JSON Datasets/pacientes.json'
)

In [ ]:
patients_no_embedded_data_json

,ID_paciente,Enfermedad_corazon,IMC,Fumador,Consumo_alcohol,AVC,Salud_fisica,Salud_mental,Dificultad_caminar,Sexo_biologico,Rango_edad,Raza,Diabetes,Actividad_fisica,Salud_general,Horas_sueño,Asma,Enfermedad_renal,Cancer_piel
0,0,No,16.60,Sí,No,No,3,30,No,Femenino,55-59,Blanca,Sí,Sí,Muy buena,5,Sí,No,Sí
1,1,No,20.34,No,No,Sí,0,0,No,Femenino,80 ó +,Blanca,No,Sí,Muy buena,7,No,No,No
2,2,No,26.58,Sí,No,No,20,30,No,Masculino,65-69,Blanca,Sí,Sí,Razonable,8,Sí,No,No
3,3,No,24.21,No,No,No,0,0,No,Femenino,75-79,Blanca,No,No,Buena,6,No,No,Sí
4,4,No,23.71,No,No,No,28,0,Sí,Femenino,40-44,Blanca,No,Sí,Muy buena,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,No,28.29,Sí,No,No,10,20,No,Femenino,65-69,Negra,Sí,Sí,Razonable,8,No,No,No
996,996,No,25.69,Sí,No,No,0,0,No,Femenino,75-79,Blanca,No,Sí,Excelente,8,No,No,No
997,997,Sí,26.99,No,No,No,1,0,No,Masculino,70-74,Blanca,No,Sí,Muy buena,8,No,No,No
998,998,No,44.29,No,No,No,30,0,Sí,Femenino,70-74,Blanca,Sí,No,Buena,6,Sí,No,No
999,999,No,25.83,No,No,No,0,0,No,Masculino,70-74,Negra,Sí,No,Excelente,7,No,No,No

In [ ]:
# Embedded data within JSON (Wrong method when embedded data)

patients_embedded_data_json_wrong_handling : pd.DataFrame = pd.read_json(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/JSON Datasets/pacientes_2.json'
)

In [ ]:
patients_embedded_data_json_wrong_handling

,Investigación,Año,Pacientes
0,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol..."
1,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio..."
2,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol..."

In [ ]:
# Embedded data within JSON (Right method when embedded data)

patients_embedded_data_json_right_handling : pd.DataFrame = pd.json_normalize(patients_embedded_data_json_wrong_handling['Pacientes'])

In [ ]:
patients_embedded_data_json_right_handling

,ID,Rango_edad,Sexo_biologico,Raza,IMC,Fumador,Consumo_alcohol,Salud_física,Salud_mental,Dificultad_caminar,Actividad_física,Salud_general,Horas_sueño,Problemas_salud
0,01,55-59,Mujer,Blanca,16.60,Sí,No,3,30,No,Sí,Muy buena,5,"[Diabetes, Asma, Cancer_piel]"
1,02,80 ó +,Mujer,Blanca,20.34,No,No,0,0,No,Sí,Muy buena,7,[AVC]
2,03,65-69,Masculino,Blanca,26.58,Sí,No,20,30,No,Sí,Muy buena,8,"[Diabetes, Asma]"

## Writing JSON (Exporting)

In [ ]:
patients_embedded_data_json_right_handling.to_json(
    'patients_embedded_data_json_right_handling.json'
)

### Example

In [ ]:
import requests
import json

In [ ]:
fruits_data : requests.models.Response = requests.get('https://fruityvice.com/api/fruit/all')

In [ ]:
result = json.loads(
    fruits_data.text
)

In [ ]:
fruits_data_as_json_dataframe = pd.DataFrame(result)

In [ ]:
pd.json_normalize(
    fruits_data_as_json_dataframe['nutritions']
)

    calories    fat  sugar  carbohydrates  protein
0         81   0.00  18.00          18.00     0.00
1         29   0.40   5.40           5.50     0.80
2         96   0.20  17.20          22.00     1.00
3         74   0.20   2.60           3.90     0.90
4         57   0.10  10.00          15.00     0.40
5        147   5.30   6.75          27.10     1.50
6         40   0.40   4.50           9.00     1.30
7         50   0.34   5.74          11.30     0.75
8         61   0.50   9.00          15.00     1.10
9         66   0.44  15.00          17.00     0.80
10        50   0.12   9.85          13.12     0.54
11        74   0.30  16.00          19.00     0.80
12        44   0.60   0.00          10.00     0.90
13        97   0.70  11.20          22.40     2.20
14        46   0.28   9.92          11.40     0.70
15        43   0.20   8.20           8.30     1.00
16        21   0.10   6.40           3.10     0.40
17        53   0.70   4.40          12.00     1.20
18        30   0.20   6.00           8.00     0.60
19        29   0.30   2.50           9.00     1.10
20        60   0.38  13.70          15.00     0.82
21        29   0.40   5.40           5.50     0.00
22        52   0.40  10.30          11.40     0.30
23        68   1.00   9.00          14.00     2.60
24        15   0.10   3.20           3.90     0.50
25        34   0.00   8.00           8.00     0.00
26        45   0.40   9.10           8.30     0.00
27        36   0.40   3.00           7.00     1.00
28        25   0.10   1.70           8.40     0.30
29        83   1.20  13.70          18.70     1.70
30        60   1.50   8.00           9.00     9.00
31        69   0.16  16.00          18.10     0.72
32        43   0.39   8.10           9.80     1.44
33        44   0.40   3.00           8.00     0.60
34       160  14.66   0.66           8.53     2.00
35        61   0.50   8.90          14.60     1.14
36        46   0.10   4.00          12.20     0.40
37        50   0.30   8.00          12.00     1.00
38        39   0.25   8.40           9.50     0.90
39        95   0.00  19.10          23.20     1.72
40        44   1.26   0.50           7.56     1.78
41       628  61.00   4.30          17.00    15.00
42        37   0.00   8.50           9.67     0.82
43        73   0.58  16.11          17.91     0.41
44        25   0.30   3.30           4.60     1.10
45        70   0.20  13.00          19.00     0.60
46        39   0.30   4.40           5.80     0.50
47        92   0.29   3.40          19.10     1.50
48        47   0.30   8.10           9.60     1.20

# HTML

## Reading HTML (Importing)

In [ ]:
# Returns all tables from website (returns an array)

movies_from_wikipedia_html_data : pd.DataFrame = pd.read_html(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/HTML Datasets/peliculas_wikipedia.html'
)

In [ ]:
# Find out how many HTML Tables there are within website

len(
    movies_from_wikipedia_html_data
)

3

In [ ]:
# Select an specific table from website (It is an array, just access to it by using its index)


top_movies_html_data : pd.DataFrame = movies_from_wikipedia_html_data[1] # Second table from the array

In [ ]:
top_movies_html_data

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5
...,...,...,...,...,...
95,The Searchers,1956,John Ford,C. V. Whitney Pictures,96
96,Bringing Up Baby,1938,Howard Hawks,RKO Radio Pictures,97
97,Unforgiven,1992,Clint Eastwood,The Malpaso Company,98
98,Guess Who's Coming to Dinner,1967,Stanley Kramer,Columbia Pictures,99
99,Yankee Doodle Dandy,1942,Michael Curtiz,Warner Bros. Pictures,100

Writing HTML (Exporting)

In [ ]:
top_movies_html_data.to_html(
    'top_movies_html_data.html',
    index=False
)

## Reading XML (Importing)

In [ ]:
# Returns all XML Tables

imbd_top_1000_xml_data : pd.DataFrame = pd.read_xml(
    '/content/drive/MyDrive/Programación Profesional/Data Science/ETL/Pandas (ETL)/Pandas E S/Datasets/XML Datasets/imdb_top_1000.xml'
)

In [ ]:
imbd_top_1000_xml_data

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

## Writing XML (Exporting)

In [ ]:
imbd_top_1000_xml_data.to_xml(
    'imbd_top_1000_xml_data.xml',
    index=False
)

In [ ]:
pd.read_xml(
   'imbd_top_1000_xml_data.xml'
)

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

## Practice 02

In [ ]:
population_wikipedia_url : str = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

population_wikipedia_response = requests.get(
    population_wikipedia_url,
    headers=headers
)

population_wikipedia_dataframe = pd.read_html(
    population_wikipedia_response.text
)

/tmp/ipython-input-984536061.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  population_wikipedia_dataframe = pd.read_html(

In [ ]:
population_wikipedia_dataframe[0]

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1754,090,12 692 000,1547,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 407 934 000,1743,-005,-1 390 000,-,-,1 408 280 000,31/12/2024,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,424,061,2 084 000,254,114,343 105 000,5/01/2026,R,www.census.gov
3,4,Indonesia,284 447 000,352,107,3 043 000,371,65,284 438 782,30/06/2025,E,www.bps.go.id
4,5,Pakistán,256 204 000,317,256,6 567 000,801,27,241 499 431,1/03/2023,C,www.pbs.gov.pk
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Islas Cocos (Australia),600,000,174,0,000,40,593,11/08/2021,C,www.citypopulation.de
242,243,Islas Ultramarinas Menores de los Estados Unidos,100,000,-496,0,000,-,190,1/04/2010,C,www.statoids.com
243,244,Islas Pitcairn (RU),30,000,-111,0,000,-,35,1/07/2023,E,www.immigration.pn
244,NaN,Mundo,8 079 659 000,10000,101,82 026 000,10000,69,8 202 019 000,5/01/2026,R,www.worldometers.info
245,N°,País (o territorio dependiente),Proyección exponencial de la población al 1/7/...,Total mun- dial (%),Cambio medio anual (%),Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción,"Censo más reciente, última estimación oficial,...",Fecha de esta última cifra de población en par...,Tipo,Enlace o hipervínculo (usualmente de tipo ofic...